#!/usr/bin/env bash
#
# Summary: Set or show the global Bun version
#
# Usage: bunenv global <version>
#
# Sets the global Bun version. You can override the global version at
# any time by setting a directory-specific version with `bunenv local'
# or by setting the `BUNENV_VERSION' environment variable.
#
# <version> should be a string matching a Bun version known to bunenv.
# The special version string `system' will use your default system Bun.
# Run `bunenv versions' for a list of available Bun versions.

set -e
[ -n "$BUNENV_DEBUG" ] && set -x

# Provide bunenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec bunenv-versions --bare
fi

BUNENV_VERSION="$1"
BUNENV_VERSION_FILE="${BUNENV_ROOT:?}/version"

if [ "$1" = "--unset" ]; then
  exec rm -f "$BUNENV_VERSION_FILE"
fi

if [ -n "$BUNENV_VERSION" ]; then
  bunenv-version-file-write "$BUNENV_VERSION_FILE" "$BUNENV_VERSION"
else
  bunenv-version-file-read "$BUNENV_VERSION_FILE" || echo system
fi
