#!/usr/bin/env bash
# Summary: Explain how the current Bun version is set
set -e
[ -n "$BUNENV_DEBUG" ] && set -x

unset BUNENV_VERSION_ORIGIN

IFS=$'\n' read -d '' -r -a scripts <<<"$(bunenv-hooks version-origin)" || true
for script in "${scripts[@]}"; do
  # shellcheck disable=SC1090
  source "$script"
done

if [ -n "$BUNENV_VERSION_ORIGIN" ]; then
  echo "$BUNENV_VERSION_ORIGIN"
elif [ -n "$BUNENV_VERSION" ]; then
  echo "BUNENV_VERSION environment variable"
else
  bunenv-version-file
fi
