#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific Bun version
#
# Usage: bunenv local <version>
#        bunenv local --unset
#
# Sets the local application-specific Bun version by writing the
# version name to a file named `.bun-version'.
#
# When you run a Bun command, bunenv will look for a `.bun-version'
# file in the current directory and each parent directory. If no such
# file is found in the tree, bunenv will use the global Bun version
# specified with `bunenv global'. A version specified with the
# `BUNENV_VERSION' environment variable takes precedence over local
# and global versions.
#
# <version> should be a string matching a Bun version known to bunenv.
# The special version string `system' will use your default system Bun.
# Run `bunenv versions' for a list of available Bun versions.

set -e
[ -n "$BUNENV_DEBUG" ] && set -x

# Provide bunenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec bunenv-versions --bare
fi

BUNENV_VERSION="$1"

if [ "$BUNENV_VERSION" = "--unset" ]; then
  rm -f .bun-version
elif [ -n "$BUNENV_VERSION" ]; then
  bunenv-version-file-write .bun-version "$BUNENV_VERSION"
else
  if version_file="$(bunenv-version-file "$PWD")"; then
    bunenv-version-file-read "$version_file"
  else
    echo "bunenv: no local version configured for this directory" >&2
    exit 1
  fi
fi
