#!/usr/bin/env bash
# Usage: bunenv completions <command> [<args>...]

set -e
[ -n "$BUNENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  bunenv-help --usage completions >&2
  exit 1
fi

# Provide bunenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec bunenv-commands
fi

COMMAND_PATH="$(type -P "bunenv-$COMMAND" "bunenv-sh-$COMMAND" | head -n1)"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide bunenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
