#!/usr/bin/env bash
set -e
[ -n "$BUNENV_DEBUG" ] && set -x

# Provide bunenv completions
if [ "$1" = "--complete" ]; then
  exec bunenv-rehash --complete
fi

shell="$(basename "${BUNENV_SHELL:-$SHELL}")"

# When bunenv shell integration is enabled, delegate to bunenv-rehash,
# then tell the shell to empty its command lookup cache.
bunenv-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
