#!/usr/bin/env bash
# Summary: List all available bunenv commands
# Usage: bunenv commands [--sh|--no-sh]
#
# List names of all bunenv commands, including 3rd-party ones found in the
# PATH or in bunenv plugins. With `--sh`, list only shell commands.
#
# This functionality is mainly meant for scripting. To see usage help for
# bunenv, run `bunenv help`.

set -e
[ -n "$BUNENV_DEBUG" ] && set -x

# Provide bunenv completions
if [ "$1" = "--complete" ]; then
  echo --sh
  echo --no-sh
  exit
fi

exclude_shell=
command_prefix="bunenv-"

if [ "$1" = "--sh" ]; then
  command_prefix="bunenv-sh-"
  shift
elif [ "$1" = "--no-sh" ]; then
  exclude_shell=1
  shift
fi

shopt -s nullglob

{
  PATH_remain="$PATH"
  # traverse PATH to find "bunenv-" prefixed commands
  while true; do
    path="${PATH_remain%%:*}"
    if [ -n "$path" ]; then
      for bunenv_command in "${path}/${command_prefix}"*; do
        bunenv_command="${bunenv_command##*bunenv-}"
        if [[ -z $exclude_shell || $bunenv_command != sh-* ]]; then
          echo "${bunenv_command##sh-}"
        fi
      done
    fi
    [[ $PATH_remain == *:* ]] || break
    PATH_remain="${PATH_remain#*:}"
  done
} | sort | uniq
