#!/usr/bin/env bash
# Summary: List existing bunenv shims
# Usage: bunenv shims [--short]

set -e
[ -n "$BUNENV_DEBUG" ] && set -x

# Provide bunenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

shopt -s nullglob

for command in "${BUNENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
