#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific Bun version
#
# Usage: bunenv shell <version>
#        bunenv shell -
#        bunenv shell --unset
#
# Sets a shell-specific Bun version by setting the `BUNENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a Bun version known to bunenv.
# The special version string `system' will use your default system Bun.
# Run `bunenv versions' for a list of available Bun versions.
#
# When `-` is passed instead of the version string, the previously set
# version will be restored. With `--unset`, the `BUNENV_VERSION`
# environment variable gets unset, restoring the environment to the
# state before the first `bunenv shell` call.

set -e
[ -n "$BUNENV_DEBUG" ] && set -x

# Provide bunenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec bunenv-versions --bare
fi

version="$1"
shell="$(basename "${BUNENV_SHELL:-$SHELL}")"

if [ -z "$version" ]; then
  if [ -z "$BUNENV_VERSION" ]; then
    echo "bunenv: no shell-specific version configured" >&2
    exit 1
  else
    echo 'echo "$BUNENV_VERSION"'
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  case "$shell" in
  fish )
    echo 'set -gu BUNENV_VERSION_OLD "$BUNENV_VERSION"'
    echo "set -e BUNENV_VERSION"
    ;;
  zsh )
    echo "typeset -g BUNENV_VERSION_OLD=\"\${BUNENV_VERSION-}\""
    echo "unset BUNENV_VERSION"
    ;;
  * )
    echo 'BUNENV_VERSION_OLD="${BUNENV_VERSION-}"'
    echo "unset BUNENV_VERSION"
    ;;
  esac
  exit
fi

if [ "$version" = "-" ]; then
  case "$shell" in
  fish )
    cat <<EOS
if set -q BUNENV_VERSION_OLD
  if [ -n "\$BUNENV_VERSION_OLD" ]
    set BUNENV_VERSION_OLD_ "\$BUNENV_VERSION"
    set -gx BUNENV_VERSION "\$BUNENV_VERSION_OLD"
    set -gu BUNENV_VERSION_OLD "\$BUNENV_VERSION_OLD_"
    set -e BUNENV_VERSION_OLD_
  else
    set -gu BUNENV_VERSION_OLD "\$BUNENV_VERSION"
    set -e BUNENV_VERSION
  end
else
  echo "bunenv: BUNENV_VERSION_OLD is not set" >&2
  false
end
EOS
    ;;
  zsh )
    cat <<EOS
if [ -n "\${BUNENV_VERSION_OLD+x}" ]; then
  if [ -n "\$BUNENV_VERSION_OLD" ]; then
    local BUNENV_VERSION_OLD_="\$BUNENV_VERSION"
    export BUNENV_VERSION="\$BUNENV_VERSION_OLD"
    BUNENV_VERSION_OLD="\$BUNENV_VERSION_OLD_"
    unset BUNENV_VERSION_OLD_
  else
    typeset -g BUNENV_VERSION_OLD="\$BUNENV_VERSION"
    unset BUNENV_VERSION
  fi
else
  echo "bunenv: BUNENV_VERSION_OLD is not set" >&2
  false
fi
EOS
    ;;
  * )
    cat <<EOS
if [ -n "\${BUNENV_VERSION_OLD+x}" ]; then
  if [ -n "\$BUNENV_VERSION_OLD" ]; then
    BUNENV_VERSION_OLD_="\$BUNENV_VERSION"
    export BUNENV_VERSION="\$BUNENV_VERSION_OLD"
    BUNENV_VERSION_OLD="\$BUNENV_VERSION_OLD_"
    unset BUNENV_VERSION_OLD_
  else
    BUNENV_VERSION_OLD="\$BUNENV_VERSION"
    unset BUNENV_VERSION
  fi
else
  echo "bunenv: BUNENV_VERSION_OLD is not set" >&2
  false
fi
EOS
    ;;
  esac
  exit
fi

# Make sure the specified version is installed.
if bunenv-prefix "$version" >/dev/null; then
  if [ "$version" != "$BUNENV_VERSION" ]; then
    case "$shell" in
    fish )
      echo 'set -gu BUNENV_VERSION_OLD "$BUNENV_VERSION"'
      echo "set -gx BUNENV_VERSION \"$version\""
      ;;
    zsh )
      echo "typeset -g BUNENV_VERSION_OLD=\"\${BUNENV_VERSION-}\""
      echo "export BUNENV_VERSION=\"$version\""
      ;;
    * )
      echo 'BUNENV_VERSION_OLD="${BUNENV_VERSION-}"'
      echo "export BUNENV_VERSION=\"$version\""
      ;;
    esac
  fi
else
  echo "false"
  exit 1
fi
